### ISSUE TITLE
Data files such as multislice/data/splines.npy and scattering/data/* are not installed

### ISSUE THREAD

**Issue by biochem-fan** [ccp4/electron-diffraction#2]
I ran `python3 setup.py install` and tried to import `blochwave`.
It gave the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/local/miniconda3/envs/pytorch/lib/python3.9/site-packages/ccp4ED-1.0.9-py3.9.egg/multislice/data/splines.npy'
```

Manually copying the corresponding file solved the issue. Perhaps the `setup.py` misses a line to copy the file.

**Comment by biochem-fan** [comment]
Similarly, `scattering/data/*` are also needed.

**Comment by ronandrevon** [comment]
oh yes the setup.py needs be updated to include them
